// <auto-generated />
using GeoReferenceAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoReferenceAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220530172051_newtablegeoreferences")]
    partial class newtablegeoreferences
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GeoReferenceAPI.Models.Estados", b =>
                {
                    b.Property<int>("idEstado")
                        .HasColumnType("int");

                    b.Property<string>("Clave_Fiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEstado");

                    b.ToTable("Estados", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("GeoReferenceAPI.Models.GeoReference", b =>
                {
                    b.Property<int>("idGeoreferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idGeoreferencia"), 1L, 1);

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<int>("idEstado")
                        .HasColumnType("int");

                    b.HasKey("idGeoreferencia");

                    b.HasIndex("idEstado");

                    b.ToTable("GeoReferences");

                    b.HasData(
                        new
                        {
                            idGeoreferencia = 1,
                            Latitud = 21.13180225,
                            Longitud = -89.50884361,
                            idEstado = 1
                        },
                        new
                        {
                            idGeoreferencia = 2,
                            Latitud = 22.302624999999999,
                            Longitud = 102.22631389999999,
                            idEstado = 1
                        },
                        new
                        {
                            idGeoreferencia = 3,
                            Latitud = 23.233599999999999,
                            Longitud = 103.3168167,
                            idEstado = 1
                        },
                        new
                        {
                            idGeoreferencia = 4,
                            Latitud = 23.23353333,
                            Longitud = 103.33355280000001,
                            idEstado = 1
                        },
                        new
                        {
                            idGeoreferencia = 5,
                            Latitud = 22.079350000000002,
                            Longitud = 102.04098329999999,
                            idEstado = 1
                        },
                        new
                        {
                            idGeoreferencia = 6,
                            Latitud = 22.397694439999999,
                            Longitud = 102.2899333,
                            idEstado = 1
                        },
                        new
                        {
                            idGeoreferencia = 7,
                            Latitud = 22.398633329999999,
                            Longitud = 102.2900556,
                            idEstado = 1
                        },
                        new
                        {
                            idGeoreferencia = 8,
                            Latitud = 21.983572219999999,
                            Longitud = 102.26676670000001,
                            idEstado = 1
                        },
                        new
                        {
                            idGeoreferencia = 9,
                            Latitud = 21.983599999999999,
                            Longitud = 102.25023059999999,
                            idEstado = 1
                        },
                        new
                        {
                            idGeoreferencia = 10,
                            Latitud = 22.616775000000001,
                            Longitud = 102.2335389,
                            idEstado = 1
                        },
                        new
                        {
                            idGeoreferencia = 11,
                            Latitud = 25.506789000000001,
                            Longitud = -102.2433589,
                            idEstado = 5
                        },
                        new
                        {
                            idGeoreferencia = 12,
                            Latitud = 25.507054109999999,
                            Longitud = -102.24439270000001,
                            idEstado = 5
                        },
                        new
                        {
                            idGeoreferencia = 13,
                            Latitud = 26.304582979999999,
                            Longitud = -103.0647895,
                            idEstado = 5
                        },
                        new
                        {
                            idGeoreferencia = 14,
                            Latitud = 26.30687434,
                            Longitud = -103.0620606,
                            idEstado = 5
                        },
                        new
                        {
                            idGeoreferencia = 15,
                            Latitud = 26.30047677,
                            Longitud = -103.05531360000001,
                            idEstado = 5
                        },
                        new
                        {
                            idGeoreferencia = 16,
                            Latitud = 26.29786489,
                            Longitud = -103.05830450000001,
                            idEstado = 5
                        },
                        new
                        {
                            idGeoreferencia = 17,
                            Latitud = 26.304641320000002,
                            Longitud = -103.06488539999999,
                            idEstado = 5
                        },
                        new
                        {
                            idGeoreferencia = 18,
                            Latitud = 26.306948349999999,
                            Longitud = -103.06221379999999,
                            idEstado = 5
                        },
                        new
                        {
                            idGeoreferencia = 19,
                            Latitud = 26.31341072,
                            Longitud = -103.0691436,
                            idEstado = 5
                        },
                        new
                        {
                            idGeoreferencia = 20,
                            Latitud = 26.310777040000001,
                            Longitud = -103.07224220000001,
                            idEstado = 5
                        },
                        new
                        {
                            idGeoreferencia = 21,
                            Latitud = 24.20180556,
                            Longitud = 107.1031389,
                            idEstado = 25
                        },
                        new
                        {
                            idGeoreferencia = 22,
                            Latitud = 2.2015833329999999,
                            Longitud = 107.10355560000001,
                            idEstado = 25
                        },
                        new
                        {
                            idGeoreferencia = 23,
                            Latitud = 24.22061111,
                            Longitud = 107.13372219999999,
                            idEstado = 25
                        },
                        new
                        {
                            idGeoreferencia = 24,
                            Latitud = 24.222388890000001,
                            Longitud = 107.13372219999999,
                            idEstado = 25
                        },
                        new
                        {
                            idGeoreferencia = 25,
                            Latitud = 24.10958333,
                            Longitud = 107.08397220000001,
                            idEstado = 25
                        },
                        new
                        {
                            idGeoreferencia = 26,
                            Latitud = 24.111138889999999,
                            Longitud = 107.08325000000001,
                            idEstado = 25
                        },
                        new
                        {
                            idGeoreferencia = 27,
                            Latitud = 24.109416670000002,
                            Longitud = 107.0788889,
                            idEstado = 25
                        },
                        new
                        {
                            idGeoreferencia = 28,
                            Latitud = 24.10727778,
                            Longitud = 107.0763611,
                            idEstado = 25
                        },
                        new
                        {
                            idGeoreferencia = 29,
                            Latitud = 24.21880556,
                            Longitud = 107.1337778,
                            idEstado = 25
                        },
                        new
                        {
                            idGeoreferencia = 30,
                            Latitud = 24.220555560000001,
                            Longitud = 107.13375000000001,
                            idEstado = 25
                        },
                        new
                        {
                            idGeoreferencia = 31,
                            Latitud = 20.623666669999999,
                            Longitud = 103.8016111,
                            idEstado = 14
                        },
                        new
                        {
                            idGeoreferencia = 32,
                            Latitud = 20.44083333,
                            Longitud = 103.92391670000001,
                            idEstado = 14
                        },
                        new
                        {
                            idGeoreferencia = 33,
                            Latitud = 20.48036111,
                            Longitud = 103.9556111,
                            idEstado = 14
                        },
                        new
                        {
                            idGeoreferencia = 34,
                            Latitud = 20.484249999999999,
                            Longitud = 103.97263890000001,
                            idEstado = 14
                        },
                        new
                        {
                            idGeoreferencia = 35,
                            Latitud = 19.883722219999999,
                            Longitud = 103.372,
                            idEstado = 14
                        },
                        new
                        {
                            idGeoreferencia = 36,
                            Latitud = 19.628194440000001,
                            Longitud = 103.7716944,
                            idEstado = 14
                        },
                        new
                        {
                            idGeoreferencia = 37,
                            Latitud = 19.647333329999999,
                            Longitud = 103.7284444,
                            idEstado = 14
                        },
                        new
                        {
                            idGeoreferencia = 38,
                            Latitud = 19.652249999999999,
                            Longitud = 103.7428056,
                            idEstado = 14
                        },
                        new
                        {
                            idGeoreferencia = 39,
                            Latitud = 19.657305560000001,
                            Longitud = 103.7916111,
                            idEstado = 14
                        },
                        new
                        {
                            idGeoreferencia = 40,
                            Latitud = 19.593499999999999,
                            Longitud = 103.81205559999999,
                            idEstado = 14
                        },
                        new
                        {
                            idGeoreferencia = 41,
                            Latitud = 25.748777780000001,
                            Longitud = 97.578944440000001,
                            idEstado = 28
                        },
                        new
                        {
                            idGeoreferencia = 42,
                            Latitud = 25.306055560000001,
                            Longitud = 97.866888889999998,
                            idEstado = 28
                        },
                        new
                        {
                            idGeoreferencia = 43,
                            Latitud = 25.306055560000001,
                            Longitud = 97.866888889999998,
                            idEstado = 28
                        },
                        new
                        {
                            idGeoreferencia = 44,
                            Latitud = 24.614388890000001,
                            Longitud = 97.915777779999999,
                            idEstado = 28
                        },
                        new
                        {
                            idGeoreferencia = 45,
                            Latitud = 25.31441667,
                            Longitud = 97.793055559999999,
                            idEstado = 28
                        },
                        new
                        {
                            idGeoreferencia = 46,
                            Latitud = 24.61452778,
                            Longitud = 97.915750000000003,
                            idEstado = 28
                        },
                        new
                        {
                            idGeoreferencia = 47,
                            Latitud = 25.299666670000001,
                            Longitud = 97.859888889999993,
                            idEstado = 28
                        },
                        new
                        {
                            idGeoreferencia = 48,
                            Latitud = 25.299666670000001,
                            Longitud = 97.859888889999993,
                            idEstado = 28
                        },
                        new
                        {
                            idGeoreferencia = 49,
                            Latitud = 25.749861110000001,
                            Longitud = 97.602166670000003,
                            idEstado = 28
                        },
                        new
                        {
                            idGeoreferencia = 50,
                            Latitud = 25.749861110000001,
                            Longitud = 97.602186110000005,
                            idEstado = 28
                        });
                });

            modelBuilder.Entity("GeoReferenceAPI.Models.GeoReference", b =>
                {
                    b.HasOne("GeoReferenceAPI.Models.Estados", "Estados")
                        .WithMany()
                        .HasForeignKey("idEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estados");
                });
#pragma warning restore 612, 618
        }
    }
}
