// <auto-generated />
using EstadoAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstadoAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EstadoAPI.Models.Estados", b =>
                {
                    b.Property<int>("idEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEstado"), 1L, 1);

                    b.Property<string>("Clave_Fiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEstado");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            idEstado = 1,
                            Clave_Fiscal = "AGS",
                            Descripcion = "AGUASCALIENTES"
                        },
                        new
                        {
                            idEstado = 2,
                            Clave_Fiscal = "BCN",
                            Descripcion = "BAJA CALIFORNIA"
                        },
                        new
                        {
                            idEstado = 3,
                            Clave_Fiscal = "BCS",
                            Descripcion = "BAJA CALIFORNIA SUR"
                        },
                        new
                        {
                            idEstado = 4,
                            Clave_Fiscal = "CAMP",
                            Descripcion = "CAMPECHE"
                        },
                        new
                        {
                            idEstado = 5,
                            Clave_Fiscal = "COAH",
                            Descripcion = "COAHUILA"
                        },
                        new
                        {
                            idEstado = 6,
                            Clave_Fiscal = "COL",
                            Descripcion = "COLIMA"
                        },
                        new
                        {
                            idEstado = 7,
                            Clave_Fiscal = "CHIS",
                            Descripcion = "CHIAPAS"
                        },
                        new
                        {
                            idEstado = 8,
                            Clave_Fiscal = "CHIH",
                            Descripcion = "CHIHUAHUA"
                        },
                        new
                        {
                            idEstado = 9,
                            Clave_Fiscal = "DF",
                            Descripcion = "DISTRITO FEDERAL"
                        },
                        new
                        {
                            idEstado = 10,
                            Clave_Fiscal = "DGO",
                            Descripcion = "DURANGO"
                        },
                        new
                        {
                            idEstado = 11,
                            Clave_Fiscal = "GTO",
                            Descripcion = "GUANAJUATO"
                        },
                        new
                        {
                            idEstado = 12,
                            Clave_Fiscal = "GRO",
                            Descripcion = "GUERRERO"
                        },
                        new
                        {
                            idEstado = 13,
                            Clave_Fiscal = "HGO",
                            Descripcion = "HIDALGO"
                        },
                        new
                        {
                            idEstado = 14,
                            Clave_Fiscal = "JAL",
                            Descripcion = "JALISCO"
                        },
                        new
                        {
                            idEstado = 15,
                            Clave_Fiscal = "MEX",
                            Descripcion = "ESTADO DE MEXICO"
                        },
                        new
                        {
                            idEstado = 16,
                            Clave_Fiscal = "MICH",
                            Descripcion = "MICHOACAN"
                        },
                        new
                        {
                            idEstado = 17,
                            Clave_Fiscal = "MOR",
                            Descripcion = "MORELOS"
                        },
                        new
                        {
                            idEstado = 18,
                            Clave_Fiscal = "NAY",
                            Descripcion = "NAYARIT"
                        },
                        new
                        {
                            idEstado = 19,
                            Clave_Fiscal = "NL",
                            Descripcion = "NUEVO LEON"
                        },
                        new
                        {
                            idEstado = 20,
                            Clave_Fiscal = "OAX",
                            Descripcion = "OAXACA"
                        },
                        new
                        {
                            idEstado = 21,
                            Clave_Fiscal = "PUE",
                            Descripcion = "PUEBLA"
                        },
                        new
                        {
                            idEstado = 22,
                            Clave_Fiscal = "QRO",
                            Descripcion = "QUERETARO"
                        },
                        new
                        {
                            idEstado = 23,
                            Clave_Fiscal = "QROO",
                            Descripcion = "QUINTANA ROO"
                        },
                        new
                        {
                            idEstado = 24,
                            Clave_Fiscal = "SLP",
                            Descripcion = "SAN LUIS POTOSI"
                        },
                        new
                        {
                            idEstado = 25,
                            Clave_Fiscal = "SIN",
                            Descripcion = "SINALOA"
                        },
                        new
                        {
                            idEstado = 26,
                            Clave_Fiscal = "SON",
                            Descripcion = "SONORA"
                        },
                        new
                        {
                            idEstado = 27,
                            Clave_Fiscal = "TAB",
                            Descripcion = "TABASCO"
                        },
                        new
                        {
                            idEstado = 28,
                            Clave_Fiscal = "TAMP",
                            Descripcion = "TAMAULIPAS"
                        },
                        new
                        {
                            idEstado = 29,
                            Clave_Fiscal = "TLAX",
                            Descripcion = "TLAXCALA"
                        },
                        new
                        {
                            idEstado = 30,
                            Clave_Fiscal = "VER",
                            Descripcion = "VERACRUZ"
                        },
                        new
                        {
                            idEstado = 31,
                            Clave_Fiscal = "YUC",
                            Descripcion = "YUCATAN"
                        },
                        new
                        {
                            idEstado = 32,
                            Clave_Fiscal = "ZAC",
                            Descripcion = "ZACATECAS"
                        },
                        new
                        {
                            idEstado = 33,
                            Clave_Fiscal = "CDMX",
                            Descripcion = "CIUDAD DE MÉXICO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
